### ISSUE TITLE
Migrate `balancer.view_trades` Abstraction

### ISSUE THREAD

**Issue by jacek0x** [balancer/dune-spellbook#3]
# Description

Migrate `balancer.view_trades` Dune abstraction to a Dune spellbook.

### Prerequisites

GitHub Issue https://github.com/balancer-labs/dune-spellbook/issues/1
GitHub Issue https://github.com/balancer-labs/dune-spellbook/issues/2

**Comment by hedgehog-jacek** [comment]
This has been merged into Dune.
