### ISSUE TITLE
create protocol fee/revenue Dune spell

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#41]
## Context
Protocol Revenue is still a pretty much neglected area on our Dune spells, queries and dashboards, while it still a fundamental metric for the Balancer DAO.

@mendesfabio  has built a few queries to measure Protocol Fee collection - which is not exactly the DAO's revenue because of the protocol fee split proposed via BIPs.

This 1st task aims to build a spell for tracking protocol fee collection and how much of it actually went to the treasury given the split back in the day.

## Requirements
- Must have daily data by pool so it's easy to join with liquidity and volume information to create more complete analysis;
- Must have the columns `protocol_fee_collected` and `protocol_revenue`  - feel free to propose other names;
  - Should follow trades and liquidity schemas where we have something like `token_amount_raw`, `token_amount`, `usd_amount` because it makes the debugging much easier in the future if there's any issues;
- Must read BIP-371 and get the information from protocol fee split there - it makes a recap of all splits so you don't have to read past proposals;
- Could try to create the spell using dbt macros so you don't have to copy and paste spells to every blockchain;

## Out of Scope
- BPTs price information, that's being handled by Troy in another task. You shouldn't exclude that information though. If a pool pays fees in BPTs, we should see it on the spell, but with empty USD values;

## Resources

- [Balancer Total Protocol Fee query](https://dune.com/queries/2697507)
- [Balancer Monthly Protocol Fee Collected query](https://dune.com/queries/2648868/4401813)
- [[BIP-371] Adjust Protocol Fee Split](https://forum.balancer.fi/t/bip-371-adjust-protocol-fee-split/4978)

**Comment by mendesfabio** [comment]
PR opened on spellbook - https://github.com/duneanalytics/spellbook/pull/4797

**Comment by viniabussafi** [comment]
PR Merged and spell created.
