### ISSUE TITLE
investigate circular dependency on bpt prices spells

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#42]
Limitations with the current bpt.prices spell are hindering our ability to use other spells, such as the protocol_fees, since it lacks information for pools with significant revenue, such as the RDNT/WETH 80/20 pool on arb.
https://github.com/balancer/dune-spellbook/issues/59 tackled the first issue, which was regarding the bpt supply spell. 
Now, we need to work on calculating bpt prices as a result of pool liquidity / bpt supply

**Comment by viniabussafi** [comment]
As expected, simply calculating the price of a BPT by dividing the pool liquidity by the bpt supply is not allowed, since it leads to a circular reference issue, as shown here: https://github.com/duneanalytics/spellbook/actions/runs/7701362598/job/20987216909?pr=5259

**Comment by viniabussafi** [comment]
I'll try an approach of replicating the liquidity spell inside the bpt prices spell, eliminating unnecessary steps for simplicity. Working on it in this [query](https://dune.com/queries/3390993)

**Comment by viniabussafi** [comment]
Working on a [PR](https://github.com/duneanalytics/spellbook/pull/5262).
Had to remove the dex prices spell as a reference (due to circular dependency), need to check how it'll affect the results

**Comment by viniabussafi** [comment]
Updates: having some troubles with the dune engine. Needed changes made to the downstream spells (trades, trabes_beta, liquidity and protocol fees). Still can't test them, though
![image](https://github.com/balancer/dune-spellbook/assets/131974393/f66c0008-e7ad-40d4-a110-5936450bc5d3)

**Comment by viniabussafi** [comment]
![image](https://github.com/balancer/dune-spellbook/assets/131974393/020c7c71-e776-40f4-b1ca-e44564625319)

**Comment by viniabussafi** [comment]
Waiting for review on Dune side. Should it take too long, I'll step away from using a macro for this spell
![image](https://github.com/balancer/dune-spellbook/assets/131974393/5ad1ac17-e66f-47a9-a74e-aaac49c76dfb)

**Comment by viniabussafi** [comment]
Restarting on https://github.com/duneanalytics/spellbook/pull/5304.
After merge, will recreate a PR for bpt prices

**Comment by viniabussafi** [comment]
Ran [PR](https://github.com/duneanalytics/spellbook/pull/5314) for basically rerunning the bpt supply spell.  It was merged but https://github.com/duneanalytics/spellbook/pull/5306 for BPT prices is still a no-go

**Comment by viniabussafi** [comment]
Was finally able to pass the tests. Now I need to check the data quality

**Comment by viniabussafi** [comment]
PR is ready for review

**Comment by viniabussafi** [comment]
PR approved and merged. spells have been tested and work
