### ISSUE TITLE
add child gauges v2 to labels

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#43]

**Comment by mendesfabio** [comment]
From Troy:

WIP:

https://dune.com/queries/3094729

1. I got all root gauges that had received a vote and then joined a table of all the decoded root gauge contracts we have on Dune;
2. Created mapping queries for each type of L2 gauge and joined them on the aforementioned table.

\* IIRC these queries are just for the v2 gauges, as I do not recall getting the streamers.

Notes:

- On Optimsim the child chain gauge contract is under balancer_v2 namespace and not balancer. The factory is under balancer namespace. I have updated the queries to use balancer_v2 but ideally it is under balancer. I tried to change it to balancer but it got rejected.
- There some empty polygonZKEVM entries because we have no contract data, obviously. Not a blocker but just noting here.
- There are 9 mainnet gauges from very early on that I was going to wait until the end to resolve.
- I think the main remaining portion is adding the logic for v1 gauges (streamer etc). I believe this is what the remaining missing pool address mappings can be attributed too.
- The namespace and contract naming was a big time sink. There are some instances of 2 different root gauges being mapped to the same recipient search for 0x8fb44263b91cac11a646cee0d44c6600cb4d5ed9 in [this query](https://dune.com/queries/3094768?sidebar=none) .
- Ideally, all of the gauge related contracts are moved to balancer namespace, removed from balancer v2 (can't be removed if used in a spell so have to change the spell to the new contract namespace first per Antonio), and have uniform naming conventions across the various contracts.

**Comment by viniabussafi** [comment]
[Query](https://dune.com/queries/3302731) ran for Arbitrum.
Initial [PR](https://github.com/duneanalytics/spellbook/pull/5037) created

**Comment by viniabussafi** [comment]
[PR](https://github.com/duneanalytics/spellbook/pull/5039) created

**Comment by viniabussafi** [comment]
Just for context, the logic is:
output_0 balancer_ethereum.CappedArbitrumRootGaugeFactory_call_create recipient --> output_0 balancer_arbitrum.ChildChainGaugeFactory_call_create pool --> 
address labels.balancer_v2_pools_arbitrum

**Comment by viniabussafi** [comment]
PR approved. Will close the issue once it's merged and tested

**Comment by viniabussafi** [comment]
Child gauges added. The only missing labels are for pools with no labels, which we will have to investigate.

![image](https://github.com/balancer/dune-spellbook/assets/131974393/ec404f42-e0b0-4056-9373-2f25dd105bb6)
