### ISSUE TITLE
create macro for balancer liquidity spells

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#44]
## Context

We have been discussing making some changes in the liquidity spell (https://github.com/balancer/dune-spellbook/issues/47).
We could take the opportunity to run the spell as macro, making our codes cleaner and as something that will help us with new spells for future versions of balancer.
There are also some lines of code that are repeated across multiple spells, for querying pool labels, prices.usd, dex.prices and bpt_prices. Being able to convert these lines into macros would be a plus, but we still need to check how the implementation will work.
This issue will be updated along the process of experimenting with these macros.

## Requirements
- Convert liquidity spell to macro
- Try to convert pool labels, prices.usd, dex.prices and bpt_prices as macros of their own, only running this macro at the final select statement of the liquidity spell, which would basically consist of:
1. day
2. pool_id
3. version
4. blockchain
5. token_address
6. token_amount_raw

- Should this task reveal as too complex, we will run a simple macro with the spell as-is, per the modifications mentioned in https://github.com/balancer/dune-spellbook/issues/47

**Comment by mendesfabio** [comment]
@viniabussafi you mentioned in #47 to be working on it, could you add some requirements here? what I would like to be aligned is with regard to how 'deep' we're in the macros approach. I mean are we simply turning the current spell into a macro, or are we going further and removing the duplicate code related to prices, symbols, etc - which would be inject using another macro. I don't have a strong opinion but just wanted to clarify what's the expected outcome.

**Comment by viniabussafi** [comment]
Context
We have been discussing making some changes in the liquidity spell (https://github.com/balancer/dune-spellbook/issues/47).
We could take the opportunity to run the spell as macro, making our codes cleaner and as something that will help us with new spells for future versions of balancer.
There are also some lines of code that are repeated across multiple spells, for querying pool labels, prices.usd, dex.prices and bpt_prices. Being able to convert these lines into macros would be a plus, but we still need to check how the implementation will work.
This issue will be updated along the process of experimenting with these macros.

Requirements
- Convert liquidity spell to macro
- Try to convert pool labels, prices.usd, dex.prices and bpt_prices as macros of their own, only running this macro at the final select statement of the liquidity spell, which would basically consist of:
1. day
2. pool_id
3. version
4. blockchain
5. token_address
6. token_amount_raw

- Should this task reveal as too complex, we will run a simple macro with the spell as-is, per the modifications mentioned in https://github.com/balancer/dune-spellbook/issues/47

**Comment by viniabussafi** [comment]
I have an initial version ready locally, but would like to have the dune team review https://github.com/balancer/dune-spellbook/issues/41 first, to make sure that I have a right grasp on the implementation of macros

**Comment by viniabussafi** [comment]
https://github.com/duneanalytics/spellbook/pull/4960 created, waiting for review.
For now, I made the choice of only converting the liquidity spell to a macro, in order to also account for https://github.com/balancer/dune-spellbook/issues/47 and https://github.com/balancer/dune-spellbook/issues/51. Still, I think converting pool labels, prices.usd, dex.prices and bpt_prices as macros of their own would be an interesting task, which would help clear a lot of our code before writing the V3 spells.

**Comment by viniabussafi** [comment]
PR merged and issue fixed
