### ISSUE TITLE
create protocol fee/revenue Dune dashboard

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#45]
## Context

Protocol Revenue is still a pretty much neglected area on our Dune spells, queries and dashboards, while it still a fundamental metric for the Balancer DAO.

@mendesfabio  has built a few queries to measure Protocol Fee collection - which is not exactly the DAO's revenue because of the protocol fee split proposed via BIPs.

@viniabussafi opened a PR to create the protocol fees spell, from which we will derive the queries to work on protocol revenue

## Requirements

- Must have an information section on the protocol fee splits (BIPs 19, 161 and 371)
- Breakdown of protocol revenues (by chain, pool, token)

## Out of Scope

Distinction between swap and yield fees

## Resources

- [Protocol Fees spell PR](https://github.com/duneanalytics/spellbook/pull/4797)
- [[BIP-371] Adjust Protocol Fee Split](https://forum.balancer.fi/t/bip-371-adjust-protocol-fee-split/4978)

**Comment by viniabussafi** [comment]
I'm working on the [dashboard](https://dune.com/balancer/protocol-revenue). 
Initial queries have been created and a bit of context on the protocol fee split has been added.
Still waiting for review on Dune side and have improvements to make on design/additional visuals
