### ISSUE TITLE
improve deployment dune crosschecking script

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#48]
## Context

A Python script has been created to fetch deployed Balancer contracts from [https://github.com/balancer/balancer-deployments](https://github.com/balancer/balancer-deployments/tree/master/tasks) and cross check them against the contracts on Dune.

- [Dune](https://dune.com/queries/2745830)
- [Script](https://colab.research.google.com/drive/1N5X8mmjmjzwhBftnmdkW7bCG2LHbW1iL)

## Requirements

- Return the [deployment txns](https://github.com/balancer/balancer-deployments/tree/master/deployment-txs);
- Add the submitted contracts table to the `evms` spell;
  - See: https://github.com/duneanalytics/spellbook/discussions/3940
- Add table columns to answer the questions Are there several instances of this contract? If so, is it created by a factory;
- Add column to identify if it should be published under balancer_v2 or balancer;
- Link to address on block explorer;
- Add the contract version column;
- Unify https://dune.com/queries/2767078 and https://dune.com/queries/2745830

**Comment by viniabussafi** [comment]
Updated [script](https://colab.research.google.com/drive/1N5X8mmjmjzwhBftnmdkW7bCG2LHbW1iL) and crosschecking [query](https://dune.com/queries/2767078?category=decoded_project&namespace=balancer_v2). Once V3 comes around, having this process solidified will come in super handy
