### ISSUE TITLE
brainstorm on Core Pools / LST liquidity dashboard

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#49]
## Context

We've talked in Barcelona about a Core Pools dashboard and recently Marketing guys reached out regarding a LST Liquidity dashboard. I'm still not sure about how to approach it because:

- There's a lot of overlap between the dashboards and metrics would be very similar;
- I wonder if wouldn't be better to highlight Core Pools and LST liquidity in other dashboards;
  - For instance, Balancer Overview could have charts/counter for % of liquidity and volume coming from LSTs.

**Comment by mendesfabio** [comment]
Regardless of the outcome here I believe it would be cool to have the Core Pools concept on Dune. We could add the `dune-upload` to a repository (managed by Maxis?) with a CSV list of pools designated as Core. Also, needs to find a way to classify/identify the liquid staking tokens - maybe that would be a `tokens.lst` table on Dune.

**Comment by viniabussafi** [comment]
###LSTs
- We could add a token type (stable, LST etc) breakdown in the [Balancer Volume - Token Breakdown dashboard](https://dune.com/balancer/volume-token-breakdown) 
- Balancer Exchange could showcase most traded token pairs

###Core Pools
- Pools overview could have a table for core pools, with link to pool analysis

**Comment by viniabussafi** [comment]
Currently working on 2 forms of defining LSTs:
- [LST tokens](https://dune.com/queries/3372708)
- [LST Pools](https://dune.com/queries/3372434)

Working on this [dashboard](https://dune.com/balancer/lsts-on-balancer). Trying to have it done by friday, as coordinated with the marketing team

**Comment by viniabussafi** [comment]
Core Pools dataset uploaded to dune via Fábio's [script](https://colab.research.google.com/drive/1tceYS8kZVi-4PzqqnZjczTVvsy2hDGie?ts=65afcd8f)

**Comment by viniabussafi** [comment]
[LSTs dashboard](https://dune.com/balancer/lst) is done
It is more introductory for now, to fit the timeframe of the marketing team also.
My idea is to have a more complex one once we have a complete bpt.prices spell, which will allow us to have a core pools dashboard with metrics such as ROI on bribes

**Comment by viniabussafi** [comment]
Updated to include missing token-pairs due to limitations on dune side + pools with LSTs paired with wstETH.
Will try to have volume metrics in eth, as well as usd

**Comment by viniabussafi** [comment]
Created a big [workaround](https://dune.com/queries/3382339) to properly calculate the TVL in [Missing LSTs](https://dune.com/queries/3382363)

**Comment by viniabussafi** [comment]
Will be complete once we have BPT prices for all pools

**Comment by viniabussafi** [comment]
Dashboard has been completed for a while and we're reaching completeness when it comes to pricing, so I'll close this issue
