### ISSUE TITLE
Same pool showing twice in graph

### ISSUE THREAD

**Issue by markusbkoch** [balancer/dune-spellbook#50]
https://dune.com/queries/2622799/4353063

I think there might be something wrong with the labels here. This is probably the same WETH/AAVE pool, labeled first as WETH/AAVE (grey) then as AAVE/WETH (blue)
![image](https://github.com/balancer/dune-spellbook/assets/34865315/45ed243d-7fcd-4ac8-bf05-a2c96952a905)

**Comment by viniabussafi** [comment]
Fixed. Will work on fixing gnosis labels for the wstETH/GNO 50/50 pool 
![image](https://github.com/balancer/dune-spellbook/assets/131974393/e5067e4b-b9c2-42b3-8e55-33be794d7342)
