### ISSUE TITLE
Add ETH values to liquidity spell

### ISSUE THREAD

**Issue by viniabussafi** [balancer/dune-spellbook#51]
With the rise of ETH prices over the last weeks, it may be interesting for us to see how our key protocol metrics (in particular for liquidity) have been behaving. So, we could add a new parameter to our dashboards to allow users to choose wether they want values displayed in USD or ETH, as they can tell different stories.
E.g. TVL in USD and ETH since Aug 1st, on this [query](https://dune.com/queries/3253442)

![image](https://github.com/balancer/dune-spellbook/assets/131974393/630dd1c9-52ef-4563-98a5-d249eff8d045)

**Comment by thetroyharris** [comment]
I agree this would be a good addition to our dashboards. However, I think that the majority of the logic needed to accomplish this should be implemented at the Spell level. I think BTC should be added as well.

**Comment by mendesfabio** [comment]
you read my mind! I thought about creating this task last week - thanks! 

Agreed it should be at Spell level as `pool_liquidity_eth` and `protocol_liquidity_eth` columns. I would say ETH is a _must have_ and BTC a _could have_ - personally, I don't want to add many columns to `balancer.liquidity` and Balancer assets should be more correlated to ETH.

**Comment by viniabussafi** [comment]
[PR](https://github.com/duneanalytics/spellbook/pull/4960) created, waiting for review.
As talked on the data standup, I've only added `protocol_liquidity_eth` and `pool_liquidity_eth` for now

**Comment by viniabussafi** [comment]
PR merged and issue fixed
