### ISSUE TITLE
fix ggAVAX and yyAVAX liquidity 

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#66]
Avalanche TVL is quite underestimated (17M on Dune vs. 24M Subgraph) because of these two Composable pools - ggAVAX and yyAVAX. It's probably related to missing decimals and/or prices for these tokens since WAVAX does have price. 

![image](https://github.com/balancer/dune-spellbook/assets/43360747/5edb1daa-b5a0-4091-af25-43b8c57a34d8)
![image](https://github.com/balancer/dune-spellbook/assets/43360747/c5288164-df5c-41f2-822c-e3dea820064c)

**Comment by viniabussafi** [comment]
Both tokens are missing on coinpaprika -- will try decreasing the dex.prices treshold on the liquidity spell while implementing a filter for outliers

**Comment by mendesfabio** [comment]
did you verify the decimals? if we fix pricing but the token hasn't been added to Dune we'll have to do it -- probably another good thing to automate. also, would double-check what are the current thresholds for sample_size both on our side and on dex.prices itself

**Comment by viniabussafi** [comment]
Created a [PR](https://github.com/duneanalytics/spellbook/pull/5386) to add both tokens to the tokens.erc20 spell

**Comment by viniabussafi** [comment]
Adding ggAVAX to the tokens.erc20 spell increased avalanche liquidity, since it had some data on dex.prices

**Comment by viniabussafi** [comment]
Now trying to create a broader solution using the rate providers to determine LST and LRT token prices. Working initially on this [query](https://dune.com/queries/3460011)

**Comment by viniabussafi** [comment]
Currently, querying both the traces table and all stable pool factories for their rate providers appears to be quite resource-intensive. I'll continue working on optimizing this process to make it more efficient. In the meantime, I've developed an alternative solution to reduce the sample size used in dex.prices. This alternative involves implementing a filter against outliers to discard occurrences where there is a 10000x increase in the price of a token between successive occurrences. You can find the details of this alternative approach in [this query](https://dune.com/queries/3472549).

**Comment by viniabussafi** [comment]
Created a [PR](https://github.com/duneanalytics/spellbook/pull/5465) to run this solution and results look good on all chains

**Comment by viniabussafi** [comment]
PR was merged and issue was fixed.
