### ISSUE TITLE
create pool aggregated data spell

### ISSUE THREAD

**Issue by mendesfabio** [balancer/dune-spellbook#70]

**Comment by viniabussafi** [comment]
working on it, making tests on this [query](https://dune.com/queries/3701027)

**Comment by mendesfabio** [comment]
hey I just did a quick review: 

1. you must select from liquidity and left join with the other tables because at the liquidity spell we ensure we have daily data and fill the gaps. right now if I search for e.g. yyAVAX pool (which seldom has trades) I don't get any results;
2. we could strive for building a `dex.metrics` spell on top of this which would contain daily data for the main metrics DEXs have -- basically swap/trading fees, swap/trading volume, and liquidity/total value locked;
3. in my opinion adding the prefix `daily_` to every metric's column is not needed - instead, we could add `_daily` as suffix to the spell name and try to follow standards set at the ERC20 balances.

<img width="335" alt="image" src="https://github.com/balancer/dune-spellbook/assets/43360747/0cfb41ba-23a7-42ed-84d3-2c4ab0948414">

**Comment by viniabussafi** [comment]
Working on a [PR](https://github.com/duneanalytics/spellbook/pull/5896)

**Comment by viniabussafi** [comment]
PR has been reviewed and fixed, just waiting to merge now

**Comment by viniabussafi** [comment]
Merged.
